name: Validate with hassfest
permissions:
  contents: read

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - uses: home-assistant/actions/hassfest@868e6cb4607727d764341a158d98872cd63fa658 # master
